package miBanco;
// Generated 22-ene-2019 13:56:57 by Hibernate Tools 4.0.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente implements java.io.Serializable {

	private Integer id;
	private String nombre;
	private Date FNac;
	private String direccion;
	private String nif;
	private Set cuentas = new HashSet(0);

	public Cliente() {
	}

	public Cliente(String nombre, Date FNac, String direccion, String nif, Set cuentas) {
		this.nombre = nombre;
		this.FNac = FNac;
		this.direccion = direccion;
		this.nif = nif;
		this.cuentas = cuentas;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Date getFNac() {
		return this.FNac;
	}

	public void setFNac(Date FNac) {
		this.FNac = FNac;
	}

	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public String getNif() {
		return this.nif;
	}

	public void setNif(String nif) {
		this.nif = nif;
	}

	public Set getCuentas() {
		return this.cuentas;
	}

	public void setCuentas(Set cuentas) {
		this.cuentas = cuentas;
	}

}
