package tablas;
// Generated 31-ene-2019 8:56:52 by Hibernate Tools 4.0.1.Final

/**
 * Estadistica generated by hbm2java
 */
public class Estadistica implements java.io.Serializable {

	private EstadisticaId id;
	private Jugador jugador;
	private Partido partido;
	private int goles;
	private int faltas;
	private int tarjAmarillas;
	private int tarjRojas;

	public Estadistica() {
	}

	public Estadistica(EstadisticaId id, Jugador jugador, Partido partido, int goles, int faltas, int tarjAmarillas,
			int tarjRojas) {
		this.id = id;
		this.jugador = jugador;
		this.partido = partido;
		this.goles = goles;
		this.faltas = faltas;
		this.tarjAmarillas = tarjAmarillas;
		this.tarjRojas = tarjRojas;
	}

	public EstadisticaId getId() {
		return this.id;
	}

	public void setId(EstadisticaId id) {
		this.id = id;
	}

	public Jugador getJugador() {
		return this.jugador;
	}

	public void setJugador(Jugador jugador) {
		this.jugador = jugador;
	}

	public Partido getPartido() {
		return this.partido;
	}

	public void setPartido(Partido partido) {
		this.partido = partido;
	}

	public int getGoles() {
		return this.goles;
	}

	public void setGoles(int goles) {
		this.goles = goles;
	}

	public int getFaltas() {
		return this.faltas;
	}

	public void setFaltas(int faltas) {
		this.faltas = faltas;
	}

	public int getTarjAmarillas() {
		return this.tarjAmarillas;
	}

	public void setTarjAmarillas(int tarjAmarillas) {
		this.tarjAmarillas = tarjAmarillas;
	}

	public int getTarjRojas() {
		return this.tarjRojas;
	}

	public void setTarjRojas(int tarjRojas) {
		this.tarjRojas = tarjRojas;
	}

}
