package tablas;
// Generated 29-ene-2019 13:48:18 by Hibernate Tools 4.0.1.Final

/**
 * EstadisticaId generated by hbm2java
 */
public class EstadisticaId implements java.io.Serializable {

	private int idPartido;
	private int licencia;

	public EstadisticaId() {
	}

	public EstadisticaId(int idPartido, int licencia) {
		this.idPartido = idPartido;
		this.licencia = licencia;
	}

	public int getIdPartido() {
		return this.idPartido;
	}

	public void setIdPartido(int idPartido) {
		this.idPartido = idPartido;
	}

	public int getLicencia() {
		return this.licencia;
	}

	public void setLicencia(int licencia) {
		this.licencia = licencia;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EstadisticaId))
			return false;
		EstadisticaId castOther = (EstadisticaId) other;

		return (this.getIdPartido() == castOther.getIdPartido()) && (this.getLicencia() == castOther.getLicencia());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdPartido();
		result = 37 * result + this.getLicencia();
		return result;
	}

}
