package tablas;
// Generated 29-ene-2019 13:48:18 by Hibernate Tools 4.0.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Jugador generated by hbm2java
 */
public class Jugador implements java.io.Serializable {

	private int licencia;
	private Equipo equipo;
	private Posicion posicion;
	private String nombre;
	private int dorsal;
	private Set estadisticas = new HashSet(0);

	public Jugador() {
	}

	public Jugador(int licencia, Equipo equipo, Posicion posicion, String nombre, int dorsal) {
		this.licencia = licencia;
		this.equipo = equipo;
		this.posicion = posicion;
		this.nombre = nombre;
		this.dorsal = dorsal;
	}

	public Jugador(int licencia, Equipo equipo, Posicion posicion, String nombre, int dorsal, Set estadisticas) {
		this.licencia = licencia;
		this.equipo = equipo;
		this.posicion = posicion;
		this.nombre = nombre;
		this.dorsal = dorsal;
		this.estadisticas = estadisticas;
	}

	public int getLicencia() {
		return this.licencia;
	}

	public void setLicencia(int licencia) {
		this.licencia = licencia;
	}

	public Equipo getEquipo() {
		return this.equipo;
	}

	public void setEquipo(Equipo equipo) {
		this.equipo = equipo;
	}

	public Posicion getPosicion() {
		return this.posicion;
	}

	public void setPosicion(Posicion posicion) {
		this.posicion = posicion;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public int getDorsal() {
		return this.dorsal;
	}

	public void setDorsal(int dorsal) {
		this.dorsal = dorsal;
	}

	public Set getEstadisticas() {
		return this.estadisticas;
	}

	public void setEstadisticas(Set estadisticas) {
		this.estadisticas = estadisticas;
	}

}
