package tablas;
// Generated 29-ene-2019 13:48:18 by Hibernate Tools 4.0.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Partido generated by hbm2java
 */
public class Partido implements java.io.Serializable {

	private Integer id;
	private Equipo equipoByIdLocal;
	private Equipo equipoByIdVisitante;
	private Competicion competicion;
	private Date fechaHora;
	private Set estadisticas = new HashSet(0);

	public Partido() {
	}

	public Partido(Equipo equipoByIdLocal, Equipo equipoByIdVisitante, Competicion competicion, Date fechaHora) {
		this.equipoByIdLocal = equipoByIdLocal;
		this.equipoByIdVisitante = equipoByIdVisitante;
		this.competicion = competicion;
		this.fechaHora = fechaHora;
	}

	public Partido(Equipo equipoByIdLocal, Equipo equipoByIdVisitante, Competicion competicion, Date fechaHora,
			Set estadisticas) {
		this.equipoByIdLocal = equipoByIdLocal;
		this.equipoByIdVisitante = equipoByIdVisitante;
		this.competicion = competicion;
		this.fechaHora = fechaHora;
		this.estadisticas = estadisticas;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Equipo getEquipoByIdLocal() {
		return this.equipoByIdLocal;
	}

	public void setEquipoByIdLocal(Equipo equipoByIdLocal) {
		this.equipoByIdLocal = equipoByIdLocal;
	}

	public Equipo getEquipoByIdVisitante() {
		return this.equipoByIdVisitante;
	}

	public void setEquipoByIdVisitante(Equipo equipoByIdVisitante) {
		this.equipoByIdVisitante = equipoByIdVisitante;
	}

	public Competicion getCompeticion() {
		return this.competicion;
	}

	public void setCompeticion(Competicion competicion) {
		this.competicion = competicion;
	}

	public Date getFechaHora() {
		return this.fechaHora;
	}

	public void setFechaHora(Date fechaHora) {
		this.fechaHora = fechaHora;
	}

	public Set getEstadisticas() {
		return this.estadisticas;
	}

	public void setEstadisticas(Set estadisticas) {
		this.estadisticas = estadisticas;
	}

}
